environment:

  global:
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\.ci\\appveyor\\run_with_env.cmd"

  matrix:
    - TARGET_ARCH: x64
      CONDA_NPY: 111
      CONDA_PY: 27
      CONDA_INSTALL_LOCN: C:\\Miniconda-x64
      DISTUTILS_USE_SDK: 1

    - TARGET_ARCH: x64
      CONDA_NPY: 111
      CONDA_INSTALL_LOCN: C:\\Miniconda37-x64
      CONDA_PY: 37

    - TARGET_ARCH: x64
      CONDA_NPY: 111
      CONDA_INSTALL_LOCN: C:\\Miniconda36-x64
      CONDA_PY: 36

platform:
  - x64

os: Previous Visual Studio 2015

init:
  - "ECHO %CONDA_INSTALL_LOCN% %CONDA_PY% %HOME% %PLATFORM%"
  - "ECHO %APPVEYOR_REPO_BRANCH%"

install:
  - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
  - cmd: conda update --yes --quiet conda
  - cmd: set PYTHONUNBUFFERED=1
  - cmd: conda config --set always_yes yes
  - cmd: conda update conda
  - cmd: conda install -q --force --no-deps psutil ruamel_yaml requests
  - cmd: conda env create -f conda env create -f environment_everything_but_dakota.yml python=$CONDA_PY
  - cmd: source activate dakota_clinic
  - cmd: cd heat
  - cmd: make install
  - cmd: pytest
  - cmd: cd ..
  - cmd: curl https://dakota.sandia.gov/sites/default/files/distributions/public/dakota-6.9-release-public-Windows.x86.zip > dakota-6.9.zip
  -

build: false

test_script:
  - "%WITH_COMPILER% pip install -e ."
  - pytest -vvv
