
name: dakota_clinic
channels:
  - defaults
  - conda-forge
  - csdms-stack
dependencies:
- python=3.6
- libgcc
- boost-gcc
- blas
- lapack
- perl
- openmpi=1.6
- dakota
- numpy
- pandas
- matplotlib
- pytest
- pyyaml
- scipy
- scikit-learn
- yaml
- pip
- spyder
- plotnine
- pip:
  - bmipy
